"""All specialty module definitions — add new specialties here without changing the engine."""

from __future__ import annotations

from app.medical_brain.specialties.base import SpecialtyModule

SPECIALTY_DEFINITIONS: tuple[SpecialtyModule, ...] = (
    SpecialtyModule(
        id="emergency_medicine",
        label="Shoshilinch yordam",
        patterns=(
            r"chest pain", r"ko['']?krak og['']?ri", r"ko['']?krakda og['']?ri",
            r"can't breathe", r"nafas qis", r"bo['']?g['']?ilib qol",
            r"103", r"tez yordam", r"emergency", r"shoshilinch",
            r"birdan yiqil", r"hushdan ket", r"unconscious", r"hushsiz",
            r"severe bleeding", r"kuchli qon ket", r"qon ketayapti",
            r"anaphylaxis", r"allergik shok",
            r"avtohalokat", r"halokat", r"travma", r"jarohat",
            r"yiqilib tush", r"ko['']?p joyi og['']?ri",
            r"tabletka ichib", r"overdose", r"ko['']?p tabletka",
            r"onam hushsiz", r"javob bermayapti",
        ),
        knowledge="ABCDE approach; time-critical diagnoses: MI, stroke, PE, sepsis, anaphylaxis, trauma.",
        guidelines="If life-threatening → minimal questions, urgent action, 103. Always identify last known well / onset time.",
        red_flags=(
            "Chest pain with diaphoresis/nausea/radiation",
            "Sudden severe headache (thunderclap)",
            "Acute focal neuro deficit",
            "Airway compromise / severe dyspnea",
            "Hemodynamic instability",
            "Altered consciousness",
        ),
        referral_rules=("Immediate ED/103 for unstable patients", "Do not delay emergency care for history"),
        investigation_suggestions=("ECG", "vitals", "glucose", "imaging as indicated"),
        expert_priorities=(
            "Stabilize / triage first",
            "Onset time and severity",
            "Red flag screen",
            "One critical discriminator only",
        ),
        avoid_early=("Long ROS", "Non-urgent differentials before stability"),
        priority=100,
    ),
    SpecialtyModule(
        id="cardiology",
        label="Kardiologiya",
        patterns=(
            r"ko['']?krak", r"chest", r"yurak", r"heart",
            r"palpit", r"aritm", r"qon bosim", r"hypertens",
            r"qorin og['']?ri.*chap qo['']?l", r"chap qo['']?l.*og['']?ri",
            r"ko['']?krag", r"ko['']?krakda", r"ko['']?kragim",
            r"hush.*ket", r"hushim ket", r"syncope", r"birdan hush",
            r"yurak urish.*tez", r"g['']?ovak",
        ),
        knowledge="Ischemic heart disease, arrhythmia, heart failure, valvular disease, hypertension.",
        guidelines="Chest pain: OPQRST + radiation + exertion + risk factors. ACS until proven otherwise if typical.",
        red_flags=(
            "Crushing chest pain >15 min",
            "Pain radiating to arm/jaw/back",
            "Syncope with chest pain",
            "Dyspnea + chest pain",
        ),
        referral_rules=("ED for ACS features", "Cardiology for arrhythmia/syncope workup"),
        investigation_suggestions=("ECG", "troponin", "echo", "Holter", "BP monitoring"),
        expert_priorities=("Pain character and radiation", "Exertional trigger", "Cardiac risk factors", "Associated dyspnea/syncope"),
        avoid_early=("Generic 1-10 before character and radiation"),
        priority=90,
    ),
    SpecialtyModule(
        id="neurology",
        label="Nevrologiya",
        patterns=(
            r"bosh\s*og['']?ri", r"boshim\s*og['']?ri", r"headache", r"migren", r"migraine",
            r"pulsatsiya", r"yorug['']?lik", r"chakka",
            r"insult", r"stroke", r"falaj",
            r"vertigo", r"aylan", r"uvish", r"uvyapti", r"neuropat",
            r"titroq", r"tremor", r"xotira", r"seizure", r"tutqanoq", r"epilep", r"nevrolog",
            r"nutq.*buzil", r"nutq buzil", r"kuchsiz", r"qo['']?l kuchsiz", r"oyoq kuchsiz",
            r"qo['']?l.*ishlamay", r"gap.*buzil", r"gapim buzildi",
            r"bo['']?yin og['']?ri", r"bel og['']?ri", r"yuz.*qiysh", r"qiyshay",
            r"eng kuchli og['']?riq", r"hayotimdagi eng kuchli",
        ),
        knowledge="Headache, stroke/TIA, vertigo, neuropathy, movement disorders, epilepsy, cognitive disorders.",
        guidelines="SNOOP for headache; FAST/time-last-well for stroke; central vs peripheral vertigo; cauda equina for back pain.",
        red_flags=(
            "Thunderclap headache",
            "Acute focal deficit",
            "Altered consciousness with headache",
            "Cauda equina symptoms",
            "First seizure",
        ),
        referral_rules=("ED for acute stroke/seizure/status", "Neurology for progressive/chronic neuro symptoms"),
        investigation_suggestions=("CT/MRI brain", "EEG", "EMG/NCS", "lumbar puncture if indicated"),
        expert_priorities=("Triage red flags", "Open narrative", "Syndrome localization", "High-yield discriminator"),
        avoid_early=("1-10 scale first", "Generic 'since when' when rich detail given"),
        priority=85,
    ),
    SpecialtyModule(
        id="endocrinology",
        label="Endokrinologiya",
        patterns=(
            r"diabet", r"qandli diabet", r"insulin", r"glycem", r"shakar",
            r"giperglik", r"giperglikem", r"giperglikemiya",
            r"qalqonsimon", r"thyroid", r"qalqon", r"hashimoto",
            r"gormon", r"endokrin",
            r"ko['']?p ichaman", r"ko['']?p siyaman",
            r"charchoq", r"sovuqqina",
            r"shakar tush", r"titroq.*terlash", r"insulin qildim", r"terlab ket",
        ),
        knowledge="Diabetes (T1/T2), thyroid disorders, adrenal, pituitary, metabolic syndrome.",
        guidelines="Diabetes + neuropathy → coordinate endocrine control AND neuro evaluation. DKA/HHS = emergency.",
        red_flags=("DKA symptoms (polyuria, vomiting, Kussmaul)", "Thyroid storm", "Hypoglycemia with altered mental status"),
        referral_rules=("Endocrinology for uncontrolled DM/thyroid", "ED for DKA/severe hypo"),
        investigation_suggestions=("HbA1c", "fasting glucose", "TSH", "CMP", "urinalysis"),
        expert_priorities=("Diabetes type and control", "Symptoms suggesting complications", "Medication adherence"),
        priority=75,
    ),
    SpecialtyModule(
        id="gastroenterology",
        label="Gastroenterologiya",
        patterns=(
            r"qorin og['']?ri", r"abdominal", r"ko['']?ngil ayn", r"nausea", r"vomit", r"qus",
            r"ich ket", r"diarr", r"qabziyat", r"constipat",
            r"jigar", r"hepat", r"pech[еe]n", r"reflyuks", r"GERD",
            r"qon.*axlat", r"melena", r"hematemesis",
            r"kuydirish", r"ovqatdan keyin", r"qorong['']?u axlat", r"qorong['']?u rangli",
            r"qorin o['']?ng past", r"o['']?ng pastga", r"sariq.*ko['']?z",
        ),
        knowledge="Upper/lower GI symptoms, liver disease, IBD, functional GI disorders.",
        guidelines="Acute abdomen, GI bleeding, jaundice with fever → urgent evaluation.",
        red_flags=("Hematemesis/melena", "Acute severe abdominal pain", "Jaundice + fever", "Weight loss + GI bleed"),
        referral_rules=("ED for GI bleed/acute abdomen", "GI for chronic/recurrent symptoms"),
        investigation_suggestions=("CBC", "LFTs", "lipase", "stool studies", "endoscopy", "imaging"),
        expert_priorities=("Pain location and character", "Bleeding evidence", "Duration and progression", "Alarm features"),
        priority=70,
    ),
    SpecialtyModule(
        id="pulmonology",
        label="Pulmonologiya",
        patterns=(
            r"nafas", r"breath", r"dyspnea", r"astma", r"asthma",
            r"yo['']?tal", r"yo['']?talish", r"chronic cough", r"surunkali yo['']?tal",
            r"hushtak", r"hemoptysis", r"qon tuflay", r"qon chiqyapti", r"qizil qon", r"pleur",
        ),
        knowledge="Asthma, COPD, pneumonia, PE, interstitial lung disease, sleep apnea overlap.",
        guidelines="Sudden dyspnea + chest pain → PE/ACS. Hemoptysis → malignancy/TB/PE workup.",
        red_flags=("Acute severe dyspnea", "Hemoptysis", "SpO2 concern", "Pleuritic chest pain"),
        referral_rules=("ED for severe dyspnea/PE concern", "Pulmonology for chronic respiratory disease"),
        investigation_suggestions=("SpO2", "CXR", "PFTs", "CT-PE if indicated"),
        expert_priorities=("Acute vs chronic", "Exertional limitation", "Cough character", "Smoking/exposure history"),
        priority=70,
    ),
    SpecialtyModule(
        id="dermatology",
        label="Dermatologiya",
        patterns=(
            r"terisi", r"skin", r"rash", r"tozma", r"qo['']?shimcha", r"dermatit",
            r"allerg", r"urticaria", r"qichish", r"itch",
            r"chang", r"acne", r"ugri", r"psoriaz",
            r"qizarish.*issiq", r"tarqal.*qizarish", r"qizarish kengay",
            r"qizar.*kuchay", r"qol.*qizar", r"qizarib",
            r"tugma.*rang", r"tugma.*shakl",
            r"pufakchalar", r"pufak", r"pemphigus", r"og['']?izda pufak",
        ),
        knowledge="Rashes, infections, inflammatory dermatoses, drug reactions, malignancy on skin.",
        guidelines="Rash + fever/systemic illness → infectious or drug reaction workup. Purpura + fever → urgent.",
        red_flags=("Purpura + fever", "Rapidly spreading rash with mucosal involvement", "Bullae with systemic symptoms"),
        referral_rules=("Dermatology for persistent/unclear rashes", "ED if Stevens-Johnson/TEN concern"),
        investigation_suggestions=("Clinical morphology", "KOH", "biopsy if indicated", "CBC if systemic"),
        expert_priorities=("Distribution and morphology", "Onset and progression", "Fever/systemic symptoms", "New medications"),
        priority=65,
    ),
    SpecialtyModule(
        id="urology",
        label="Urologiya",
        patterns=(
            r"siydik", r"urin", r"prostata", r"prostat",
            r"qon.*siydik", r"hematur", r"disuria",
            r"testis", r"moya", r"ereks", r"moyak",
            r"belda o['']?tkir", r"bel.*o['']?tkir", r"renal colic", r"to['']?lqinli og['']?riq",
        ),
        knowledge="UTI, hematuria, BPH, kidney stones, urologic malignancy.",
        guidelines="Painless hematuria → urologic malignancy workup. Testicular mass → urgent urology.",
        red_flags=("Painless hematuria", "Testicular mass", "Anuria/retention with pain", "Fever + flank pain"),
        referral_rules=("Urology for hematuria/mass", "Urgent urology malignancy workup for painless hematuria", "ED for retention/sepsis"),
        investigation_suggestions=("Urinalysis", "culture", "PSA if indicated", "imaging"),
        expert_priorities=("Dysuria vs hematuria", "Flank pain", "Stream changes", "Fever"),
        priority=60,
    ),
    SpecialtyModule(
        id="gynecology",
        label="Ginekologiya",
        patterns=(
            r"hayz", r"menstru", r"regl", r"homilador", r"pregnant",
            r"pelvik", r"discharge", r"akint", r"ginekolog",
            r"ovary", r"tuxumdon", r"menopauz",
            r"qorin past", r"homiladorlik testi",
        ),
        knowledge="Menstrual disorders, pregnancy-related symptoms, pelvic pain, infections.",
        guidelines="Pregnancy + pain/bleeding → ectopic/urgency until excluded. Postmenopausal bleeding → malignancy workup.",
        red_flags=("Postmenopausal bleeding", "Pregnancy with severe pain/bleeding", "Severe pelvic pain + fever"),
        referral_rules=("OB/GYN for pregnancy/pelvic pathology", "Urgent gynecology malignancy workup for postmenopausal bleeding", "ED for ectopic concern"),
        investigation_suggestions=("UPT", "pelvic exam", "ultrasound", "CBC"),
        expert_priorities=("LMP/pregnancy status", "Pain timing in cycle", "Bleeding pattern", "Fever/discharge"),
        priority=65,
    ),
    SpecialtyModule(
        id="pediatrics",
        label="Pediatriya",
        patterns=(
            r"bolam", r"farzand", r"bola", r"child", r"pediatr",
            r"chaqaloq", r"infant", r"yosh bol",
            r"bolam.*isitma", r"bola.*qus", r"bola.*tutqanoq", r"haftalik", r"oylik",
            r"gapira olmay", r"qiynalyapti",
        ),
        knowledge="Age-specific differentials; higher index for serious illness in young children.",
        guidelines="Fever in infant <3 months → urgent evaluation. Dehydration, lethargy, poor feeding → urgent.",
        red_flags=("Fever in neonate/young infant", "Lethargy/poor feeding", "Non-blanching rash in child", "Respiratory distress in child"),
        referral_rules=("Pediatric ED for sick child", "Pediatrician for routine/chronic"),
        investigation_suggestions=("Age-appropriate workup", "vitals with percentiles"),
        expert_priorities=("Age", "Hydration", "Activity/feeding", "Fever duration"),
        priority=80,
    ),
    SpecialtyModule(
        id="orthopedics",
        label="Ortopediya",
        patterns=(
            r"suyak", r"bone", r"fracture", r"sinish", r"uzilish",
            r"bo['']?g['']?im", r"joint", r"tizza", r"tizza og['']?ri",
            r"bel og['']?ri", r"yelka", r"bilak", r"yiqil", r"tushdim",
            r"chiqib ketdi", r"dislocation",
            r"artrit.*travma", r"sport.*jarohat",
        ),
        knowledge="Fractures, joint injuries, overuse, degenerative joint disease.",
        guidelines="Neurovascular compromise, open fracture, hip fracture in elderly → urgent.",
        red_flags=("Open fracture", "Neurovascular deficit", "Unable to bear weight after trauma", "Hot swollen monoarthritis (septic until proven)"),
        referral_rules=("Orthopedics/ED for trauma", "Rheumatology if inflammatory arthritis concern"),
        investigation_suggestions=("X-ray", "MRI if soft tissue/ligament", "joint aspiration if septic concern"),
        expert_priorities=("Mechanism of injury", "Weight bearing", "Deformity/swelling", "Neurovascular status"),
        priority=60,
    ),
    SpecialtyModule(
        id="rheumatology",
        label="Revmatologiya",
        patterns=(
            r"revmat", r"artrit", r"arthritis", r"lupus", r"autoimmun",
            r"bog['']?im.*shish", r"joint.*swell", r"gout", r"podagra",
            r"shishgan.*issiq", r"issiq.*shish",
        ),
        knowledge="Inflammatory arthritis, connective tissue disease, crystal arthropathy.",
        guidelines="Hot monoarthritis → septic vs gout until proven. Systemic symptoms + multi-joint → autoimmune workup.",
        red_flags=("Hot swollen joint with fever", "Multi-system autoimmune features", "Jaw claudication/vision loss (GCA)"),
        referral_rules=("Rheumatology for chronic inflammatory", "ED/joint aspiration for acute hot joint"),
        investigation_suggestions=("ESR/CRP", "RF/anti-CCP", "ANA", "uric acid", "synovial fluid"),
        expert_priorities=("Joint pattern (mono/oligo/poly)", "Morning stiffness duration", "Systemic symptoms", "Skin/nail changes"),
        priority=55,
    ),
    SpecialtyModule(
        id="psychiatry",
        label="Psixiatriya",
        patterns=(
            r"depress", r"depres", r"suicid", r"o['']?z joniga", r"o['']?zini o['']?ldir",
            r"o['']?ldirmoqchi", r"o['']?zimni o['']?ldir",
            r"halusinat", r"paranoy", r"bipolar", r"psix",
            r"panika", r"panic", r"umidsiz",
            r"tabletka ichib", r"ko['']?p tabletka", r"overdose",
        ),
        knowledge="Depression, anxiety, psychosis, bipolar disorder, safety assessment.",
        guidelines="Always assess safety (suicide/self-harm). Rule out organic causes (thyroid, substance, neuro).",
        red_flags=("Active suicidal ideation with plan", "Psychosis with agitation", "Catatonia", "Postpartum psychosis"),
        referral_rules=("Crisis services for active suicide risk", "Psychiatry for persistent symptoms"),
        investigation_suggestions=("Safety assessment", "substance screen", "TSH if indicated"),
        expert_priorities=("Safety screen first", "Duration and functional impact", "Sleep/appetite", "Substance/medication review"),
        avoid_early=("Long psychiatric checklist tone"),
        priority=50,
    ),
    SpecialtyModule(
        id="ent",
        label="LOR",
        patterns=(
            r"quloq", r"ear", r"burun", r"nose", r"tomoq", r"throat",
            r"sinusit", r"tonsillit", r"hoarse", r"ovoz o['']?zgar", r"ovozim",
            r"eshitish", r"hearing",
        ),
        knowledge="Otitis, sinusitis, pharyngitis, hearing loss, vertigo overlap with neuro.",
        guidelines="Sudden hearing loss → urgent ENT. Unilateral throat pain + dysphagia → consider deep space infection.",
        red_flags=("Sudden sensorineural hearing loss", "Stridor/airway compromise", "Peritonsillar abscess features"),
        referral_rules=("ENT for hearing loss/chronic ENT", "ED for airway compromise"),
        investigation_suggestions=("Otoscopy", "audiometry", "throat exam"),
        expert_priorities=("Laterality", "Duration", "Fever", "Hearing change vs vertigo"),
        priority=55,
    ),
    SpecialtyModule(
        id="ophthalmology",
        label="Oftalmologiya",
        patterns=(
            r"ko['']?z", r"eye", r"vision", r"ko['']?rish", r"bulut",
            r"glauk", r"katarakt", r"qizarish.*ko['']?z",
        ),
        knowledge="Red eye, vision loss, glaucoma, retinal detachment, diabetic eye disease.",
        guidelines="Acute painless vision loss → retinal artery occlusion/retinal detachment urgency. Painful red eye + nausea → acute glaucoma.",
        red_flags=("Acute painless vision loss", "Acute painful red eye", "Flashing lights/floaters + curtain", "Eye trauma with vision change"),
        referral_rules=("Ophthalmology/ED same-day for acute vision loss"),
        investigation_suggestions=("Visual acuity", "IOP", "fundoscopy", "slit lamp"),
        expert_priorities=("Pain vs painless", "Unilateral vs bilateral", "Onset speed", "Trauma history"),
        priority=70,
    ),
    SpecialtyModule(
        id="infectious_diseases",
        label="Yuqumli kasalliklar",
        patterns=(
            r"isitma", r"fever", r"temp", r"infekts", r"infection",
            r"virus", r"bakter", r"COVID", r"COVID-19", r"gripp", r"flu",
            r"TB", r"sil", r"travel.*fever",
        ),
        knowledge="Fever workup, sepsis, tropical infections, immunocompromised host.",
        guidelines="Fever + rash + systemically unwell → urgent. Immunocompromised + fever → treat as emergency.",
        red_flags=("Fever + rigors + hypotension", "Fever + rash + mucosal involvement", "Immunocompromised + fever", "Neutropenic fever"),
        referral_rules=("ID consult for complex/recurrent infections", "ED for sepsis concern"),
        investigation_suggestions=("CBC", "blood cultures", "CRP", "imaging", "travel/exposure history"),
        expert_priorities=("Fever pattern", "Travel/exposure", "Immunocompromised status", "Localizing symptoms"),
        priority=75,
    ),
    SpecialtyModule(
        id="internal_medicine",
        label="Ichki kasalliklar",
        patterns=(
            r"charchoq", r"fatigue", r"holsiz", r"weight loss",
            r"general", r"umumiy holsiz", r"ko['']?p kasallik",
            r"sababsiz", r"noma['']?lum",
        ),
        knowledge="Undifferentiated symptoms, multi-system disease, initial workup coordination.",
        guidelines="Weight loss + night sweats → malignancy/infection/endocrine. Fatigue → broad organic screen before attributing to stress.",
        red_flags=("Unintentional weight loss", "Night sweats", "Persistent fever of unknown origin"),
        referral_rules=("Refer to organ-specific specialty once localized", "IM for undifferentiated complex cases"),
        investigation_suggestions=("CBC", "CMP", "TSH", "ESR/CRP", "targeted based on symptoms"),
        expert_priorities=("Timeline", "Constitutional symptoms", "Medication review", "Systems review targeted"),
        priority=40,
    ),
    SpecialtyModule(
        id="oncology",
        label="Onkologiya",
        patterns=(
            r"saraton", r"cancer", r"onko", r"tumor",
            r"limfa.*shish", r"lymph.*swell", r"neoplasm",
            r"sababsiz.*kg",
        ),
        knowledge="Red flag symptoms for malignancy, staging awareness, treatment side effects.",
        guidelines="Unexplained weight loss, persistent lymphadenopathy, hemoptysis, postmenopausal bleeding → malignancy workup.",
        red_flags=("Progressive unexplained weight loss", "Persistent lymphadenopathy", "Hemoptysis", "New focal mass"),
        referral_rules=("Oncology after tissue diagnosis", "Fast-track workup for red flags"),
        investigation_suggestions=("Imaging", "biopsy", "tumor markers only if indicated"),
        expert_priorities=("Duration", "Progression", "B symptoms", "Prior cancer history"),
        priority=60,
    ),
    SpecialtyModule(
        id="general_surgery",
        label="Umumiy jarrohlik",
        patterns=(
            r"append", r"apend", r"hernia", r"grilja",
            r"cholecyst", r"o['']?t pufak", r"gallbladder",
            r"jarroh", r"surgery", r"operats",
            r"qorin.*og['']?ri", r"qattiq.*qorin", r"qorin.*qattiq",
        ),
        knowledge="Acute abdomen, hernias, gallstones, surgical emergencies.",
        guidelines="Acute abdomen with peritoneal signs → surgical emergency. Right lower quadrant pain → appendicitis in differential.",
        red_flags=("Peritoneal signs", "Rigid abdomen", "Incarcerated hernia", "Charcot triad (cholangitis)"),
        referral_rules=("Surgical ED consult for acute abdomen", "Elective surgery referral when stable"),
        investigation_suggestions=("Ultrasound", "CT abdomen", "LFTs", "WBC"),
        expert_priorities=("Pain location migration", "Fever", "Vomiting", "Last meal/bowel function"),
        priority=65,
    ),
    SpecialtyModule(
        id="nephrology",
        label="Nefrologiya",
        patterns=(
            r"siydik.*kamay|oliguri|anuri|proteinuri|nefrot",
            r"bel.*tomonda|flank|pielonefrit|glomerul",
            r"dializ|giyohvand|transplant.*buyrak",
            r"shish.*yuz|yuz.*shish|buyrak",
            r"giperkalemi|elektrolit.*buyrak",
        ),
        knowledge="AKI, CKD, glomerulonephritis, nephrotic syndrome, electrolyte disorders, dialysis.",
        guidelines="Oliguria + systemic illness → AKI workup urgent. Nephrotic-range proteinuria → biopsy pathway.",
        red_flags=("Anuria", "Hyperkalemia with ECG changes", "Pulmonary edema from renal failure", "Rapidly rising creatinine"),
        referral_rules=("Nephrology for AKI/CKD/proteinuria", "ED for life-threatening electrolytes or pulmonary edema"),
        investigation_suggestions=("Urinalysis", "creatinine/eGFR", "electrolytes", "renal ultrasound"),
        expert_priorities=("Urine output", "Edema distribution", "Hematuria vs proteinuria", "Medication nephrotoxins"),
        priority=62,
    ),
    SpecialtyModule(
        id="hematology",
        label="Gematologiya",
        patterns=(
            r"anemiya|qon kam|gemoglobin|gematokrit",
            r"koagul|qon.*suyultir|petexi|purpura|ekimoz",
            r"leykem|limfoma|limfa.*shish|spleen",
            r"qon.*yaxshilanmay|transfuz",
            r"vena.*tromb|DVT|PE.*qon",
        ),
        knowledge="Anemia workup, coagulopathy, thrombocytopenia, hematologic malignancy, VTE.",
        guidelines="Pancytopenia + fever → neutropenic sepsis urgency. New lymphadenopathy + B symptoms → malignancy workup.",
        red_flags=("Neutropenic fever", "Disseminated intravascular coagulation", "Massive hemoptysis/hematemesis", "Spontaneous bleeding on anticoagulation"),
        referral_rules=("Hematology for cytopenias/malignancy suspicion", "ED for active major bleeding or neutropenic sepsis"),
        investigation_suggestions=("CBC with differential", "peripheral smear", "coagulation panel", "LDH/uric acid if malignancy"),
        expert_priorities=("Bleeding vs clotting phenotype", "Medication/anticoagulant history", "B symptoms", "Family history"),
        priority=63,
    ),
    SpecialtyModule(
        id="obstetrics",
        label="Akusherlik",
        patterns=(
            r"homilador.*(?:qon|og['']?riq|harakat|suv|isitma)",
            r"homiladorlik.*(?:hafta|trimestr|36w|34w|28w)",
            r"preeklamps|eklamps|hellp|platsenta",
            r"homilador.*nafas|homilador.*bosim",
            r"qisqarish|tugruq|labour|contractions",
        ),
        knowledge="Antepartum complications, fetal wellbeing, hypertensive disorders of pregnancy, labor concerns.",
        guidelines="Any bleeding in pregnancy → urgent OB evaluation. Headache/visual changes + pregnancy → pre-eclampsia until excluded.",
        red_flags=("Antepartum hemorrhage", "Decreased fetal movement", "Seizure in pregnancy", "Severe hypertension in pregnancy"),
        referral_rules=("Obstetric emergency for bleeding/preeclampsia/decreased FM", "Labor and delivery for ROM/contractions"),
        investigation_suggestions=("Fetal heart rate", "blood pressure", "urinalysis protein", "ultrasound"),
        expert_priorities=("Gestational age", "Fetal movement", "Bleeding amount", "Blood pressure and neuro symptoms"),
        priority=78,
    ),
    SpecialtyModule(
        id="intensive_care",
        label="Intensiv terapiya",
        patterns=(
            r"ressusitats|intubats|ventilyator|ICU|ITU|intensiv",
            r"sepsis.*shok|septik shok|multiorgan",
            r"ARDS|akut.*respirator|yomon.*nafas.*hush",
            r"qon bosim.*past.*hush|laktat|vazopressor",
            r"komada|GCS.*past|organ yetishmov",
        ),
        knowledge="Shock, sepsis, respiratory failure, multi-organ dysfunction, critical care stabilization.",
        guidelines="Sepsis with hypotension → immediate resuscitation. Acute respiratory failure → airway and oxygenation first.",
        red_flags=("Septic shock", "Acute respiratory failure", "Altered mental status with hypotension", "Lactate elevation with end-organ hypoperfusion"),
        referral_rules=("Emergency/ICU for shock or respiratory failure", "Direct ICU admission for organ failure"),
        investigation_suggestions=("ABG", "lactate", "blood cultures", "chest imaging", "bedside echo if available"),
        expert_priorities=("Hemodynamics", "Airway", "Source control", "Organ perfusion"),
        priority=85,
    ),
)

# Known multi-specialty combinations (boost secondary routing)
MULTI_SPECIALTY_HINTS: tuple[tuple[tuple[str, ...], tuple[str, ...]], ...] = (
    (("diabet", "neuropat", "uvish"), ("endocrinology", "neurology")),
    (("diabet", "shakar", "oyoq uvish"), ("endocrinology", "neurology")),
    (("diabet", "uvish"), ("endocrinology", "neurology")),
    (("diabet", "uvyapti"), ("endocrinology", "neurology")),
    (("qandli diabet", "uvyapti"), ("endocrinology", "neurology")),
    (("diabet", "qo['']?l.*uvyapti"), ("endocrinology", "neurology")),
    (("ko['']?krak", "qo['']?l", "uvish"), ("emergency_medicine", "cardiology", "neurology")),
    (("ko['']?krak og['']?ri", "chap qo['']?l"), ("emergency_medicine", "cardiology")),
    (("tozma", "isitma"), ("dermatology", "infectious_diseases")),
    (("qizar", "isitma"), ("dermatology", "infectious_diseases", "emergency_medicine")),
    (("rash", "fever"), ("dermatology", "infectious_diseases")),
    (("terisi", "isitma"), ("dermatology", "infectious_diseases")),
    (("nafas", "ko['']?krak"), ("emergency_medicine", "cardiology", "pulmonology")),
    (("hush", "ket"), ("emergency_medicine", "cardiology", "neurology")),
    (("bel og['']?ri", "oyoq"), ("neurology", "orthopedics", "emergency_medicine")),
    (("bel og['']?ri", "siydik"), ("neurology", "emergency_medicine", "urology")),
    (("bolam", "isitma"), ("pediatrics", "infectious_diseases", "emergency_medicine")),
    (("homilador", "qon"), ("gynecology", "emergency_medicine")),
    (("surunkali yo['']?tal",), ("pulmonology",)),
    (("avtohalokat",), ("emergency_medicine", "orthopedics", "general_surgery")),
    (("javob bermayapti", "isitma"), ("emergency_medicine", "neurology", "infectious_diseases")),
    (("tabletka ichib",), ("emergency_medicine", "psychiatry")),
)
