"""Twenty neurology scenarios for Clinical Brain evaluation vs expert interview."""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class NeurologyScenario:
    id: str
    title: str
    opening_message: str
    category: str
    expert_opens_with: str
    expert_priority_topics: list[str]
    common_ai_mistake: str
    why_ai_mistakes: str
    improvement: str
    red_flag_hints: list[str] = field(default_factory=list)


SCENARIOS: tuple[NeurologyScenario, ...] = (
    NeurologyScenario(
        id="01_thunderclap",
        title="Thunderclap headache (SAH screen)",
        opening_message="Boshim birdan juda qattiq og'riyapti, hayotimdagi eng kuchli og'riq",
        category="headache",
        expert_opens_with="Acknowledge urgency; ask if truly sudden (peak in seconds) and any neck stiffness, vomiting, vision change.",
        expert_priority_topics=["triage", "onset_sudden", "max_intensity_timing", "neuro_symptoms"],
        common_ai_mistake="Asks 'where is the pain — forehead or temple?' first",
        why_ai_mistakes="Question tree lists location early; GPT follows reference order instead of SNOOP triage",
        improvement="Screen thunderclap + neuro symptoms before topography",
        red_flag_hints=["stroke", "thunderclap"],
    ),
    NeurologyScenario(
        id="02_migraine",
        title="Typical migraine",
        opening_message="Chakkamda og'riyapti, ko'ngil aynish bor, yorug'likdan qo'rqaman",
        category="headache",
        expert_opens_with="Confirm pattern: unilateral, nausea, photophobia — then frequency and disability.",
        expert_priority_topics=["discriminator", "pattern", "frequency", "functional_impact"],
        common_ai_mistake="Asks onset date before acknowledging migraine features already given",
        why_ai_mistakes="Template always starts with 'since when' regardless of rich first message",
        improvement="Reflect back features patient gave; ask frequency/duration of episodes next",
    ),
    NeurologyScenario(
        id="03_tension",
        title="Tension-type headache",
        opening_message="Peshonamda bosuvchi og'riq, stress paytida kuchayadi",
        category="headache",
        expert_opens_with="Explore chronicity, daily pattern, stress/sleep — low urgency unless red flags.",
        expert_priority_topics=["narrative", "chronicity", "stress_sleep", "triage_screen"],
        common_ai_mistake="Immediate 1-10 severity scale",
        why_ai_mistakes="Knowledge reference lists severity as required early item",
        improvement="Skip numeric scale early; ask daily vs episodic and stress context",
    ),
    NeurologyScenario(
        id="04_stroke_acute",
        title="Acute stroke symptoms",
        opening_message="O'ng qo'lim ishlmayapti, nutqim buzildi, 1 soat oldin boshlandi",
        category="stroke",
        expert_opens_with="Confirm timeline, last well, call emergency — minimal questions.",
        expert_priority_topics=["triage", "onset_time", "last_well", "current_deficit"],
        common_ai_mistake="Continues routine headache-style history",
        why_ai_mistakes="Classifier may misroute; brain doesn't force emergency pathway hard enough",
        improvement="Stroke presentation → emergency assessment + time last well only",
        red_flag_hints=["stroke", "focal"],
    ),
    NeurologyScenario(
        id="05_tia",
        title="Transient weakness (TIA workup)",
        opening_message="Kecha 10 daqiqa qo'lim uiydi, hozir yaxshi",
        category="stroke",
        expert_opens_with="Exact timing, recurrence risk factors, anticoagulants, BP/diabetes.",
        expert_priority_topics=["onset_time", "duration", "risk_factors", "recurrence"],
        common_ai_mistake="Asks unrelated review of systems",
        why_ai_mistakes="GPT tries to complete generic tree instead of TIA-specific workup",
        improvement="Focus on vascular risk and event timing",
    ),
    NeurologyScenario(
        id="06_cauda_equina",
        title="Back pain + red flags",
        opening_message="Bel og'riyapti, oyoqlarim uiydi, hojatxonaga qiyin",
        category="low_back_pain",
        expert_opens_with="Cauda equina screen: bilateral leg weakness, saddle numbness, retention — urgent.",
        expert_priority_topics=["triage", "cauda_equina", "bilateral_symptoms", "bladder"],
        common_ai_mistake="Asks 'how long has back hurt'",
        why_ai_mistakes="Onset is first item in back pain tree; triage not prioritized",
        improvement="Bladder/bowel + bilateral symptoms before chronicity",
        red_flag_hints=["cauda", "weakness"],
    ),
    NeurologyScenario(
        id="07_sciatica",
        title="Radiculopathy / sciatica",
        opening_message="Beldan oyoqqa otib og'riyapti, o'tirganda yomon",
        category="low_back_pain",
        expert_opens_with="Radiation pattern, leg vs back predominance, neuro exam equivalents in history.",
        expert_priority_topics=["discriminator", "radiation", "position", "neuro_symptoms"],
        common_ai_mistake="Generic severity 1-10",
        why_ai_mistakes="Low-yield scale substituted for radiation pattern",
        improvement="Ask which leg, below knee, numbness weakness",
    ),
    NeurologyScenario(
        id="08_cervical_myelopathy",
        title="Neck pain + cord symptoms",
        opening_message="Bo'ynim og'riyapti, qo'llarim uiydi, sigaret chekaman",
        category="neck_pain",
        expert_opens_with="Myelopathy: hand clumsiness, gait, Lhermitte, progression.",
        expert_priority_topics=["triage", "myelopathy", "upper_limb_symptoms", "progression"],
        common_ai_mistake="Only local neck pain questions",
        why_ai_mistakes="Category neck_pain triggers pain tree not cord compression logic",
        improvement="Always screen upper/lower limb neuro symptoms for neck pain",
    ),
    NeurologyScenario(
        id="09_bppv",
        title="Positional vertigo (BPPV)",
        opening_message="Boshim aylanadi, yotqanda ayniqsa",
        category="vertigo",
        expert_opens_with="Episodic vs constant; seconds vs minutes; positional trigger.",
        expert_priority_topics=["discriminator", "timing", "positional", "hearing"],
        common_ai_mistake="'Since when' as first question",
        why_ai_mistakes="Onset prioritized over timing pattern — key for BPPV vs central",
        improvement="First: episode length and position trigger",
    ),
    NeurologyScenario(
        id="10_central_vertigo",
        title="Central vertigo red flags",
        opening_message="Bosh aylanishi doimiy, yurishda yiqilaman, bosh og'rig'i bor",
        category="vertigo",
        expert_opens_with="Continuous vertigo + ataxia + headache → central, urgent evaluation.",
        expert_priority_topics=["triage", "continuous", "ataxia", "headache"],
        common_ai_mistake="Asks about ear fullness only",
        why_ai_mistakes="Peripheral vertigo bias in knowledge reference",
        improvement="Screen central signs before peripheral discriminators",
        red_flag_hints=["central"],
    ),
    NeurologyScenario(
        id="11_bells_palsy",
        title="Facial weakness",
        opening_message="Yuzimning bir tomoni harakatsiz, kecha tongda sezdim",
        category="facial_nerve_palsy",
        expert_opens_with="Whole face vs lower face only (stroke); ear pain; hyperacusis.",
        expert_priority_topics=["discriminator", "upper_vs_lower_face", "onset", "ear_symptoms"],
        common_ai_mistake="Doesn't distinguish Bell's vs stroke",
        why_ai_mistakes="GPT lacks explicit forehead sparing question priority",
        improvement="Forehead movement question early",
    ),
    NeurologyScenario(
        id="12_neuropathy_diabetic",
        title="Diabetic neuropathy",
        opening_message="Oyoqlarim uiydi, kechasi yomon, diabetim bor",
        category="neuropathy",
        expert_opens_with="Symmetric stocking-glove, diabetes control, progression, pain vs numb.",
        expert_priority_topics=["context", "symmetry", "diabetes", "progression"],
        common_ai_mistake="Asks unrelated headache questions",
        why_ai_mistakes="Wrong complaint category or generic tree",
        improvement="Confirm symmetry and diabetes first — patient already volunteered DM",
    ),
    NeurologyScenario(
        id="13_tremor_rest",
        title="Rest tremor (Parkinson concern)",
        opening_message="Qo'lim dam olganda titraydi, sekin yuraman",
        category="tremor",
        expert_opens_with="Rest vs action tremor; bradykinesia; unilateral onset.",
        expert_priority_topics=["discriminator", "rest_vs_action", "bradykinesia", "onset"],
        common_ai_mistake="Only asks age and onset",
        why_ai_mistakes="Misses rest/action — key Parkinson discriminator patient hinted",
        improvement="Follow patient's clue: rest tremor → ask stiffness, gait, small handwriting",
    ),
    NeurologyScenario(
        id="14_memory_mci",
        title="Memory concern",
        opening_message="Xotiram yomonlashdi, kalitlarni unutaman",
        category="memory_problems",
        expert_opens_with="Functional impact (finances, meds); informant; acute vs gradual.",
        expert_priority_topics=["functional_impact", "onset_pace", "orientation", "mood_sleep"],
        common_ai_mistake="Mini mental test questions in chat",
        why_ai_mistakes="GPT improvises exam instead of history",
        improvement="ADL questions; gradual vs sudden; family confirmation",
    ),
    NeurologyScenario(
        id="15_sleep_apnea",
        title="Excessive daytime sleepiness",
        opening_message="Kunduz uxlab qolaman, xurrak chalayman deyishadi",
        category="sleep_disorders",
        expert_opens_with="Snoring, apneas witnessed, BMI, driving safety.",
        expert_priority_topics=["discriminator", "snoring_apnea", "daytime_sleepiness", "safety"],
        common_ai_mistake="Generic insomnia questions",
        why_ai_mistakes="Sleep tree conflates insomnia and hypersomnia",
        improvement="Match hypersomnia cluster — snoring, apneas, morning headache",
    ),
    NeurologyScenario(
        id="16_panic_somatic",
        title="Anxiety with neurological symptoms",
        opening_message="Yurak urishi, bosh aylanadi, o'lishimdan qo'rqaman",
        category="anxiety",
        expert_opens_with="Rule out organic (arrhythmia, vertigo); panic pattern; still screen neuro red flags.",
        expert_priority_topics=["triage", "organic_screen", "panic_pattern", "function"],
        common_ai_mistake="Pure reassurance without brief organic screen",
        why_ai_mistakes="Psych category skips somatic overlap",
        improvement="Brief syncope/arrhythmia screen then anxiety pattern",
    ),
    NeurologyScenario(
        id="17_depression_fatigue",
        title="Depression overlap",
        opening_message="Hech narsaga qiziqmayman, uxlay olmayman, bosimim tushyapti",
        category="depression",
        expert_opens_with="Safety screen; distinguish depression from sleep apnea, thyroid, neuro.",
        expert_priority_topics=["safety", "sleep", "somatic", "duration"],
        common_ai_mistake="Long psychiatric questionnaire tone",
        why_ai_mistakes="GPT uses checklist not conversational psychiatry",
        improvement="Warm open question on daily function + safety",
    ),
    NeurologyScenario(
        id="18_first_seizure",
        title="First seizure",
        opening_message="Hushimdan ketdim deyishadi, tilim qisilgan",
        category="other_neurological",
        expert_opens_with="Witness account, duration, post-ictal, fever, alcohol, meds.",
        expert_priority_topics=["triage", "witness", "postictal", "provocation"],
        common_ai_mistake="Treats as headache workup",
        why_ai_mistakes="other_neurological lacks seizure-specific strategy",
        improvement="Seizure-first triage block when keywords present",
        red_flag_hints=["seizure", "consciousness"],
    ),
    NeurologyScenario(
        id="19_topic_switch",
        title="Mid-consultation topic change",
        opening_message="Belim og'riyapti",
        category="headache",
        expert_opens_with="Clarify new vs continuing complaint before clinical questions.",
        expert_priority_topics=["conversation", "complaint_clarification"],
        common_ai_mistake="Continues headache questions for back pain",
        why_ai_mistakes="Intent layer may miss; brain receives wrong category context",
        improvement="Handled by conversation intent layer + category update",
    ),
    NeurologyScenario(
        id="20_greeting_mid",
        title="Greeting during active consult",
        opening_message="Assalomu alaykum",
        category="headache",
        expert_opens_with="Social greeting + resume or new problem — no clinical question yet.",
        expert_priority_topics=["conversation", "session_choice"],
        common_ai_mistake="Jumps to 'since when does head hurt'",
        why_ai_mistakes="Session continues collecting without intent gate",
        improvement="Conversation intent before clinical brain (already implemented)",
    ),
)
